repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            CHANGELOG.tpl.md|
            CHANGELOG.md|
            CHANGELOG-dev.md
          )$
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: # optional: list of Conventional Commits types to allow
          - build
          - change
          - chore
          - ci
          - deprecate
          - docs
          - feat
          - fix
          - perf
          - refactor
          - remove
          - revert
          - security
          - style
          - test
  - repo: https://github.com/python-poetry/poetry
    rev: "1.4"
    hooks:
      - id: poetry-check
